# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 03:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='id',
        ),
        migrations.AddField(
            model_name='reply',
            name='at',
            field=models.ForeignKey(default=datetime.datetime(2016, 7, 14, 3, 56, 52, 230333, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cafe.Post'),
            preserve_default=False,
        ),
    ]
