# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 05:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cafe', '0005_auto_20160714_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='added_at',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='adder',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='post',
        ),
        migrations.AddField(
            model_name='reply',
            name='at',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cafe.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reply',
            name='writer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
